### ISSUE TITLE
Unable to configure communication protocol

### ISSUE THREAD

**Issue by haitan981** [enscada/IndigoSCADA#1]
I have installed the latest version of Indigo SCADA. But the software interface is different from the manual. For example, IndigoSCADA has the word Client added, in the System Control menu there is no System Manager item.
Could you help me fix those issues.

![image](https://github.com/enscada/IndigoSCADA/assets/44091731/20f1eeac-f5af-4a0a-91eb-d06d3de7bf91)
![image](https://github.com/enscada/IndigoSCADA/assets/44091731/5f260009-3a39-4959-8027-6240965a79b5)

**Comment by enscada** [comment]
Hi,

the only updated manual available is here: 

http://www.enscada.com/a7khg9/IndigoSCADA_user_manual.pdf

Best regards,

apa
